#!/bin/bash
set -euxo pipefail

exec >> postBuildOut.txt
exec 2>&1

pushd jupytergraffiti
npm install && npm run build && \
    jupyter nbextension install graffiti-dist && \
    jupyter nbextension enable graffiti-dist/graffiti
popd

